Pull Request for TSE Review of Bubble Sort Solution
Calvinoea/Bubble-Sort-Ruby pull request #1
Opened 2020-04-23 14:49 UTC by Calvinoea

Hello. We (@hillarioh and I) are making a pull request for review of our solution for the Bubble Sort project/task as part of the Microverse/Odin Curriculum. 

The solution has been made using Ruby. Stickler and rubucop were used to check for errors in the code. 

Thank you for your time and review.

2020-04-23 19:16 UTC, mosesogwo requested changes
**HI @Calvinoea, @hillarioh, good work :+1:**

Enable stickler for this repository and ensure that all tests pass and please see my comments on your files.

_**Kindly make those changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-04-23 19:16 UTC, mosesogwo commented on README.md
> +- GitHub [here](https://github.com/hillarioh/)
It'd be better to use your GitHub handle instead of "here"

2020-04-23 19:16 UTC, mosesogwo commented on README.md
> +- GitHub [here](https://github.com/calvinoea/)
It'd be better to use your GitHub handle instead of "here"

2020-04-23 19:16 UTC, mosesogwo commented on bubblesort.rb
> +    puts ''
Remove the print and puts. The return of the sorted array is sufficient.

2020-04-24 02:52 UTC, majovanilla requested changes
Hi team! :wave: 

## You did a *great* job on this project! 💜 

However, I can't see the bubble_sort_by method in your project!!

You need to implement this method, too before approving your project.

Please work on this requirement and request a new code review! :smile: 


If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-04-24 08:58 UTC, whiz25 requested changes
## Great Job
You have made the requested changes by the previous reviewers but we still need to fix some failing edge cases before we can merge this PR.
- [x] enable stickler in this repo and make sure all tests pass
- [ ] add a `bubble_sort` method. We need two working methods in this repo.
- [x] check my comments for more suggestions

### Martin Afani

2020-04-24 08:59 UTC, whiz25 commented on bubblesort.rb
> +end
- [ ] bubble_sort_by method is implemented and working (Screenshot from Odin)
- [ ] sorts an array of numbers in increasing order
```ruby
unsorted = (1..10).to_a.reverse!
bubble_sort(unsorted) == unsorted.sort # should return true
```
- [ ] sorts an array by accepting a block
```ruby
unsorted = %w[hi hello hey]
bubble_sort_by(unsorted) { |left, right| left.length - right.length } == %w[hi hey hello] # should return true
```
- [ ] raises an error if block is not given
```ruby
unsorted = %w[hi hello hey]
bubble_sort_by(unsorted) == raise_error # should return true
```

2020-04-24 14:17 UTC, stratospherique requested changes
### Great progress @Calvinoea :clap: :clap: However, some of the changes requested by the previous reviewer were not implemented. Check :arrow_down: 

* [ ] bubble_sort_by method is implemented and working ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_bubble_sort/sortBy.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-1))
- You need to come up with your own version of **bubble_sort_by** that accept blocks and raises an error when no block is given. Read the description in the link above, It should help you understand what are the requirements for this method.

### That's it :relieved: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-04-25 07:14 UTC, mosesogwo approved these changes
**Hi @Calvinoea, Congratulations! Your project is approved:trophy:**

You can now merge to master

**Cheers:stars:**

### Status: Approved :heavy_check_mark:

2020-04-25 07:24 UTC, merged